version: "3.7"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    env_file:
      - ./env/db.env
    ports:
      - 5432:5432
    volumes:
      - ./apps/db/pgdata:/var/lib/postgresql/data
      - ./apps/db/schema_init.sql:/docker-entrypoint-initdb.d/1_init.sql
  api:
    container_name: api
    build: ./apps/api
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./apps/api/:/code
      - ./env:/code/env
    environment:
      FLASK_ENV: development
    depends_on:
      - postgres
  dashboard:
    container_name: dashboard
    build: ./apps/dashboard
    volumes:
      - ./apps/dashboard:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres
      - api
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   env_file:
  #     - ./env/pgadmin.env
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - postgres
  #   logging:
  #     driver: "none"
